name: Aerial Dreams
favicon: null
layout_spectrum: 0.7853660895489156
typography_spectrum: 0.8183952590916306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#58799a'
    - '#9dcdf1'
    - '#475055'
    - '#1b1c20'
  brandStrength: 0
  lightness: 0
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
