name: Aerial Dreams
favicon: null
layout_spectrum: 0.34039
typography_spectrum: 0.08385
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0a0a'
    - '#444444'
    - '#1383b3'
    - '#868887'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
