name: Aerial Dreams
favicon: null
layout_spectrum: 0.34039
typography_spectrum: 0.51624
title: Aerial Dreams
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1919'
    - '#fffffe'
    - '#767675'
    - '#3f3d3d'
    - '#b6b6b5'
  brandStrength: 0.0625
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
