name: Aerial Dreams
favicon: null
layout_spectrum: 0.34039
typography_spectrum: 0.30923
title: 'Aerial Dreams, by Nick Adams'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1919'
    - '#fffffe'
    - '#767675'
    - '#3f3d3d'
    - '#b6b6b5'
  brandStrength: 0
  lightness: 0.0625
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
